### ISSUE TITLE
No implementation for org.elasticsearch.client.Client was bound.

### ISSUE THREAD

**Issue by rbraaf** [sega-yarkin/graylog-plugin-dnstap#1]
Installed the plugin with Graylog version 2.3.0 and everything worked fine. After updating to 2.3.1 I started to get the error in the subject line after restart. Moving the jar file out of the plugin directory allows Graylog to successfully startup again. Any thoughts? 

OS: CentOS7
Graylog: 2.3.1
Plugin: 0.0.2

**Comment by malaiwah** [comment]
Same on 2.4.0.

It seems this plugin brings back the Anonymous Usage Statistics somehow as per this log snippet.

> 2018-01-10 21:33:01,692 INFO o.g.b.CmdLineTool [main] Loaded plugin: Anonymous Usage Statistics 2.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
> 2018-01-10 21:33:01,944 INFO o.g.b.CmdLineTool [main] Running with JVM arguments: -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dapp=graylog -Dlog4j.configurationFile=/usr/local/etc/graylog/server/log4j2.xml -Xms256m -Xmx1g -XX:-OmitStackTraceInFastThrow -XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:+CMSConcurrentMTEnabled -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+ResizeTLAB -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseFastAccessorMethods -XX:+UseParNewGC -XX:CMSInitiatingOccupancyFraction=75 -XX:NewRatio=1
> 2018-01-10 21:33:02,117 INFO o.h.v.i.u.Version [main] HV000001: Hibernate Validator 5.1.3.Final
> 
> 2018-01-10 21:33:03,918 ERROR o.g.b.CmdLineTool [main] Guice error (more detail on log level debug): No implementation for org.elasticsearch.client.Client was bound.
> Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) No implementation for org.elasticsearch.client.Client was bound.
>   while locating org.elasticsearch.client.Client
>     for the 1st parameter of org.graylog.plugins.usagestatistics.collectors.ElasticsearchCollector.<init>(ElasticsearchCollector.java:53)
>   at org.graylog.plugins.usagestatistics.UsageStatsModule.configure(UsageStatsModule.java:50) (via modules: org.graylog2.shared.bindings.PluginBindings -> org.graylog.plugins.usagestatistics.UsageStatsModule)
> 
> 1 error
> 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
> 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
> 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
> 	at com.google.inject.Guice.createInjector(Guice.java:99)
> 	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
> 	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
> 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
> 	at org.graylog2.bootstrap.Main.main(Main.java:44)

**Comment by malaiwah** [comment]
I believe this is "just" because the dnstap jar includes an old version of a graylog built-in plugin.
I "just" rebuilt the dnstap jar ( available at https://github.com/malaiwah/graylog-plugin-dnstap/releases/tag/v0.0.3 ) and it works to me now on Graylog 2.4.0

**Comment by sega-yarkin** [comment]
@rbraaf Sorry for not responding, I'm very busy now, and our system administrators haven't used this plugin yet (due to some problem with unbound). Can you try new build from malaiwah?

@malaiwah Thanks for your interest, I haven't thought that so many people use this plugin)

Can you share information from which software (+ version) you're receiving dnstap traffic and how many messages per second an input is handling? Thanks!

**Comment by rbraaf** [comment]
@sega-yarkin No worries, I just tried @malaiwah's new build and Graylog started up on version 2.4.0.

Thanks everyone for your assistance.
